# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fullscreen": "00_core.ipynb",
         "display_all": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rbracco.github.io/nbpro/"

git_url = "https://github.com/rbracco/nbpro/tree/master/"

def custom_doc_links(name): return None
