# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['fullscreen', 'display_all']

# Cell
def fullscreen(width=100):
    setting = f"<style>.container {{ width:{width}% !important; }}</style>"
    display(HTML(setting))

# Cell
#‘all’, ‘last’, ‘last_expr’ or ‘none’, ‘last_expr_or_assign’
#credit Stas Bekman
def display_all(mode):
    InteractiveShell.ast_node_interactivity = "all" if mode else "last_expr"
display_all(True)
x, y = 12, 20
x
y