# IPython log file

get_ipython().run_line_magic('pinfo', '%xdel')
get_ipython().run_line_magic('pinfo', '%xmode')
get_ipython().run_line_magic('pinfo', '%more')
get_ipython().run_line_magic('more', 'error.py')
get_ipython().run_line_magic('page', 'error.py')
import error
get_ipython().run_line_magic('pinfo2', 'error')
get_ipython().run_line_magic('pinfo', '%macro')
get_ipython().run_line_magic('pinfo', '%notebook')
get_ipython().run_line_magic('pinfo', '%logon')
get_ipython().run_line_magic('pinfo2', '%logstart')
get_ipython().run_line_magic('pinfo', '%logstart')
x = 36
y = 32
print(x+y)
get_ipython().run_line_magic('logstop', '')
get_ipython().run_line_magic('logstart', '')
x = 36
y = 32
print(x+y)
get_ipython().run_line_magic('logstop', '')
get_ipython().run_line_magic('logstart', '')
get_ipython().system('echo "hello"')
get_ipython().run_line_magic('pinfo', '%ldir')
get_ipython().run_line_magic('pinfo', '%killbgscripts')
get_ipython().run_line_magic('pinfo', '%edit')
get_ipython().run_line_magic('edit', '')
get_ipython().run_line_magic('pinfo', '%ed')
get_ipython().run_line_magic('pinfo', '%dhist')
get_ipython().run_line_magic('pinfo', '%ddir')
get_ipython().run_line_magic('pinfo', '%dirs')
get_ipython().run_line_magic('dirs', '')
get_ipython().run_line_magic('dhist', '')
get_ipython().run_line_magic('pinfo', '%copy')
get_ipython().run_line_magic('pinfo2', '%copy')
get_ipython().run_line_magic('pinfo', '%connect_info')
get_ipython().run_line_magic('connect_info', '')
get_ipython().run_line_magic('pinfo', '%config')
get_ipython().run_line_magic('config', '')
get_ipython().run_line_magic('config', 'MagicsManager')
get_ipython().run_line_magic('config', '')
get_ipython().run_line_magic('config', 'DisplayFormatter')
get_ipython().run_line_magic('config', '')
get_ipython().run_line_magic('config', 'AliasManager')
get_ipython().run_line_magic('config', '')
get_ipython().run_line_magic('config', 'HistoryManager')
get_ipython().run_line_magic('config', 'IPCompleter')
get_ipython().run_line_magic('config', 'OSMagics')
get_ipython().run_line_magic('config', 'PrefilterManager')
get_ipython().run_line_magic('config', 'ScriptMagics')
get_ipython().run_line_magic('config', 'ZMQInteractiveShell')
from IPython.core.interactiveshell import InteractiveShell
get_ipython().run_line_magic('config', 'StoreMagics')
get_ipython().run_line_magic('pinfo', '%conda')
get_ipython().run_line_magic('pinfo', '%colors')
get_ipython().run_line_magic('pinfo', '%cls')
get_ipython().run_line_magic('pinfo', '%bookmark')
get_ipython().run_line_magic('bookmark', 'data_folder ..')
get_ipython().run_line_magic('bookmark', '-l')
get_ipython().system(' -b data_folder')
get_ipython().run_line_magic('cd', '-b data_folder')
get_ipython().run_line_magic('bookmark', '-l')
get_ipython().run_line_magic('cd', 'tutorials')
get_ipython().run_line_magic('pwd', '')
get_ipython().run_line_magic('pinfo', '%autosave')
get_ipython().run_line_magic('pinfo', '%autocall')
get_ipython().run_line_magic('pinfo', '%autoawait')
get_ipython().run_line_magic('pinfo', '%alias_magic')
get_ipython().run_line_magic('alias_magic', 'pastebin pb')
get_ipython().run_line_magic('alias_magic', 'pb pastebin')
